### PR TITLE
create travis with docker

### PR DESCRIPTION
**Pull request by candyYMMA**
Run the bbsnode in Docker in automation via travis CI.

### CODE REVIEW

**Comment by gz-c** [comment]
travis has go 1.9 environments, refer to the travis files in the other repos

**Comment by gz-c** [comment]
Here is a badge for the README
[Build Status](https://travis-ci.org/skycoin/bbs)

Any reason you are merging to branch `ui_automation` and not to `master`?

**Comment by candyYMMA** [comment]
Sorry but how do I take this badge using the .svg extension into the readME ? I saw how it was done it the skycoin/skycoin ReadMe.
Evan and I taught we first give it a run in a separate brunch before merging to master. The plan is to add E2E protractor tests to all the bbs UI.

**Comment by gz-c** [comment]
@candyYMMA sorry i updated the text for the badge

**Pull request merged**
